### PR TITLE
Added EFGQuadrupolarProduct class to efg.py.

### PR DESCRIPTION
**Pull request by davedavemckay**

### CODE REVIEW

**Comment by stur86** [comment]
Just a few questions before I decide whether to merge this:

* is there a particular reason for using this and not simply `EFGAsymmetry`? It's the same quantity except I think for the sign.
* why was the docstring to Vzz modified? Is that a mistake? Or is the diff acting up and it actually wasn't like that?
* is the docstring to EFGEta actually done properly? It looks like the definition is missing, I only see `eta = ` and then nothing.

**Comment by davedavemckay** [comment]
> Just a few questions before I decide whether to merge this:
> 
> * is there a particular reason for using this and not simply `EFGAsymmetry`? It's the same quantity except I think for the sign.
eta is the conventional quantity
> * why was the docstring to Vzz modified? Is that a mistake? Or is the diff acting up and it actually wasn't like that?
There should be no change to Vzz - see any changes as typos.
> * is the docstring to EFGEta actually done properly? It looks like the definition is missing, I only see `eta = ` and then nothing.
I forgot to go back and fill this in. It should read:
"eta = (Vxx-Vyy)/Vzz"

**Comment by davedavemckay** [comment]
I have fixed the "eta =" docstring line and added EFGQuadrupolarProduct

**Comment by stur86** [comment]
Ok, so now it's just the EFGQuadrupolarProduct then. Merging!

**Pull request merged**
